- os_network:
      cloud: openstack
      state: present
      name: ext_network
      external: true
      admin_state_up: yes
      provider_network_type: flat
      provider_physical_network: datacentre
- os_subnet:
    cloud: openstack
    state: present
    network_name: ext_network
    name: external_subnet
    cidr: 192.0.2.254
    ip_version: 4
    gateway_ip: 192.0.2.254
    enable_dhcp: no
    allocation_pool_start: 192.0.2.150
    allocation_pool_end: 192.0.2.200
    dns_nameservers:
      - 8.8.8.8
- os_network:
    - os_network:
      cloud: openstack
      state: present
      name: int_network
      external: false
      admin_state_up: yes
      provider_network_type: null
      provider_physical_network: null
- os_subnet:
    cloud: openstack
    state: present
    network_name: int_network
    name: int_subnet
    cidr: 172.16.0.0/24
    ip_version: 4
    gateway_ip: null
    enable_dhcp: yes
    allocation_pool_start: null
    allocation_pool_end: null
    dns_nameservers:
      - 8.8.8.8

- os_router:
    cloud: openstack
    state: present
    name: router
    network: ext_network
    interfaces: int_subnet
